### ISSUE TITLE
Examples need to wait for themes to load

### ISSUE THREAD

**Issue by phxnsharp** [structurizr/ui#1]
In order for documents to draw correctly, you need to wait for the themes to load before loading the diagram. 

https://github.com/structurizr/ui/blob/ab04e8982bb7e3d016b30dc48dd1e21890b30333/examples/diagram-basic.html#L34

```javascript
    $.ajax({url: 'https://raw.githubusercontent.com/structurizr/ui/main/examples/big-bank-plc.json',
    success: function(data){
        structurizr.workspace = new structurizr.Workspace(JSON.parse(data));
        structurizr.ui.loadThemes(function() {
            const diagram = new structurizr.ui.Diagram('diagram', false, function() {
                diagram.changeView('Containers');
            });
        });
    }});
});
```

**Comment by simonbrowndotje** [comment]
This shouldn't be the case ... `https://raw.githubusercontent.com/structurizr/ui/main/examples/big-bank-plc.json` has no themes.

**Comment by phxnsharp** [comment]
Add a person to the diagram. The person will show as a box instead of person unless you do this.

**Comment by simonbrowndotje** [comment]
The `Containers` diagram in that example already has a person on it.

<img width="1195" alt="Screenshot 2023-02-03 at 13 44 38" src="https://user-images.githubusercontent.com/1009874/216618507-78227d02-fcb0-4d9f-baf2-7359bd1ee7de.png">

Is this a problem with a workspace of your own, or does the `examples/diagram-basic.html` file in the repo not work for you?

**Comment by phxnsharp** [comment]
I do not reproduce the problem in the sample repo here. I am using this from a Hugo static site, so the race condition must be quite different. I do not at this time have a reproduction recipe I can share. If I have time I can try to create one.
