### ISSUE TITLE
Relationship Description / Technology Rendering

### ISSUE THREAD

**Issue by nei-l** [structurizr/ui#10]
Hi,

I recently pulled the latest docker image (tag: 3020) and have noticed that rendering of a relationship's description and technology are overlapping when the font size is increased. This wasn't the case previously (although I'm afraid I can't tell you which version introduced the change as I haven't pulled the latest for some time).

Here's an example using fontSize=45 and a width=400: -

![image](https://user-images.githubusercontent.com/1281823/225395791-5efccb24-415d-4ed3-8673-b2b4ecf871d0.png)

In the previous version there was a point where this overlap occurred (due to the description being split over multiple lines) and increasing the width fixed it so that it was workable. In the recent version changing the width seems to have no impact with the overlap and even with a single line of text in the description (as in the example above) this occurs.

Is it a known issue? It's making a lot of my views rather hard to read.

**Comment by simonbrowndotje** [comment]
You're welcome - thanks for including an appropriate amount of detail in the issue!
