### ISSUE TITLE
containerInstance and softwareSystemIntance description are not rendered

### ISSUE THREAD

**Issue by yvesaston** [structurizr/ui#19]
### Description

When a deployment view is rendered, the description of the related container to a containerInstance is shown, meanwhile the containerInstance description is lost - not displayed on the diagram nor in the tool tip.
Same applies to softwareSystem/softwareSystemInstance

Expected behavior:

- if a containerInstance includes a set description, render it.
- if a systemSoftwareInstance includes a set description, render it.

Note that infrastructureNode description is properly rendered. Both being children of deploymentNode, so personally I view as inccoherent not rendering a containerInstance description meanwhile rendering an infrastructureNode description. 

### Steps to reproduce

1. create a containerInstance including a description.
2. include it in a deployment view
3. render the deployment view. The containerInstance description is not rendered.
4. activate tooltip display. The containerInstance description is not displayed within the pop-up tip.

Repeat the same for a softwareSystemInstance. 

### Screenshot

![Screenshot 2023-05-04 130425](https://user-images.githubusercontent.com/123368955/236186560-e0b2e31f-2da0-4f9d-9481-720108021c3f.png)

### Code sample

```text
workspace "Deployment description" {
    !identifiers hierarchical

    model {
        systemA = softwareSystem "System A" "Description for System A" {
            container1 = container "Container 1" "Container 1 description"
            container2 = container "Container 2" "Container 2 description"
        }
        systemB = softwareSystem "System B" "System B description"

        deploymentEnvironment qa {
            deploymentNode node1 "Deployment node 1" {
                containerInstance systemA.container1 {
                    description "Container 1 instance description"
                }
                containerInstance systemA.container2
            }
            deploymentNode node2 "Deployment node 2" {
                softwareSystemInstance systemB {
                    description "System B Instance description"
                }
                softwareSystemInstance systemB
            }
            deploymentNode node3 "Deployment node 3" {
                infrastructureNode infraNode "Infrastructure node description"
            }
        }
    }
    views {
        deployment * qa "qa" "deployment view" {
            include *
            autoLayout
        }
    }
}
```

### Configuration

Structurizr Lite
- build: 3047 (2023-04-06T07:33:20Z)
- structurizr-java: v1.24.1
- structurizr-dsl: v1.30.1
- structurizr-import: v1.4.1

### Severity

Minor

### Priority

Medium

### Resolution

I have no budget, please fix this for free

**Comment by simonbrowndotje** [comment]
I've added some code to make this happen in the browser-based UI, but if you're using any of the PlantUML, Mermaid, etc exporters, you'll need to open new issues to have the same support added to them.

**Comment by yvesaston** [comment]
Hi Simon, thanks and noted. That is enough for me for now,
