### ISSUE TITLE
Highlight the relationship label when hovering over the line

### ISSUE THREAD

**Issue by jillesmc** [structurizr/ui#20]
### Description

Use case:
When a diagram has a considerable number of elements and some element has a considerable number of relationships, the autoLayout feature isn't always good at not overlapping relationship lines and their labels.
And while documenting existing software, I often want to make use of the diagram before fine-tuning the layout.

Because the lines are cluttered it is difficult to see what label is related to the line I'm hovering. "/

Solution:
Would be nice to highlight the relationship label when hovering over the line.

### Priority

Low

### Resolution

I'm willing to add this feature myself and raise a PR

**Comment by jillesmc** [comment]
Hi @simonbrowndotje. I hope you are doing well.
I'm not sure if you are still following the Issues and PRs in this repository, but I would love to see your comments about this issue/PR when you have time. :)
Tks.

**Comment by simonbrowndotje** [comment]
> I'm not sure if you are still following the Issues and PRs in this repository

I am ... May/June are busy with workshops/conferences though, so I don't have much time for non-priority support at the moment. Sorry!

**Comment by jillesmc** [comment]
No worries.
Thanks for letting me know.  ;)
