### ISSUE TITLE
"Export to offline HTML page" in Decisions page 

### ISSUE THREAD

**Issue by superbull** [structurizr/ui#22]
### Description

Currently the "Export to offline HTML page" function only available in the _Documentation_ page.
Can we also have it in the _Decisions_ page?

### Priority

Medium

### Resolution

I have no budget, please add this feature for free

**Comment by prlcutting** [comment]
Kinda related to this request... is there a way to include the ADRs into the documentation in Structurizr Lite?

I would like to be able to hand off a document to new hires to bring them up to speed on our product. The "Export to offline HTML page" fits the bill (almost) perfectly for this. The documentation (following @simonbrowndotje's excellent [Software Architecture for Developers](https://softwarearchitecturefordevelopers.com/) e-books suggests a "Decision Log" chapter. However, when using Structurizr, the ADRs are managed separately (for good reasons), and therefore are not part of the documentation. It would be nice to have a switch somewhere that lets Structurizr Lite users elect to "embed" the ADRs as part of the "Decision Log" section/chapter to form one comprehensive reference. I can see some people wanting to keep them separate, while others may want to join them, hence the switch option.

What do you think?
