### ISSUE TITLE
Add mouse wheel as a way to zoom into or out of sub-components.

### ISSUE THREAD

**Issue by ets614** [structurizr/ui#35]
### Description

Greetings,

New to the world of C4 diagramming, but really impressed how quickly I was able to get off-and-running with Structurizr in a matter of minutes and am very excited about this tool!

I have been getting the hang of driving and stepping-through the diagrams in the Structurizr UI via the keyboard shortcuts (https://structurizr.com/help/keyboard-shortcuts), and was wondering if ever considered getting the mouse wheel more involved for zooming in/out?

In particular the "dream" I have always had with diagramming in my career (as well as to go along with the C4 "maps of your code" Google Maps analogy) is UI effect where mouse-wheeling/zooming in towards a component explodes(?)/decomposes(?) it into its sub-components.  Mouse-wheeling/zooming out doing the opposite.

(I think the additional key part to creating this map-zoom-in/out effect is ensuring all the other dependencies/entities remain in their original locations allowing the audience to maintain context. But probably outside scope of this feature request.)

Thoughts?

Regards,
Evan

### Priority

Low

### Resolution

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment]
This was actually my original goal, but the implementation is a bit beyond me I'm afraid, particularly when you get past a handful of boxes and arrows. You might want to take a look at Ilograph as it has the sort of UI you're looking for ... you can use the Structurizr CLI's [Ilograph export](https://docs.structurizr.com/export/ilograph) to convert a Structurizr workspace for use with the tool.

**Comment by ets614** [comment]
Copy all. Thanks for the redirect! Very slick UI effects for Ilograph at least from the samples/demoes. Will hopefully get a chance to try it out more tomorrow.

Makes sense; kind of figured UIs like this take a while to make and still really like the portability/support Structurizr seems to offer; e.g. being able to bounce between other UIs like D2 as well.

Thank you again. Happy to close this issue if you want as think this will get me what I need for day 1.
