### ISSUE TITLE
Graph view has no navigation controls

### ISSUE THREAD

**Issue by ODiogoSilva** [structurizr/ui#44]
### Description

When visualising diagram in the acyclic dependency graph, there are no controls in the UI to do things like panning the canvas, zooming in/out, search etc. Mouse/keyboard inputs also don't work to this effect, except when clicking on a node, which highlights the relationships and is quite nice.

This makes it impossible to properly visualise even small diagram (see figure above with only 4 components)

### Steps to reproduce

The issue is prevent on the Demo graph in Structurizr page

1. Go to https://structurizr.com/dsl
2. Click on the "Structuriz Graph" option on the top right
3. Observe that there are no controls to navigate the canvas

### Screenshot

<img width="1260" alt="image" src="https://github.com/structurizr/ui/assets/1532292/210e7232-2004-40c7-bf9e-8bd9dfea4aa6">

### Severity

Major

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by simonbrowndotje** [comment]
The graph view doesn't work well on the demo page given the small size, but it should work okay outside of this (i.e. Lite, on-premises, cloud). And it also doesn't work well when you have elements that are disconnected from the main graph (I can see this in your screenshot). You can press `Space` to open the quick find dialog, which can help highlight an element though.

**Comment by ODiogoSilva** [comment]
Thank you for the quick reply.

The `Space` tip is great and mitigates some of the navigation issues. I'm currently trying this on Lite, but is it expected behaviour that there is no way to zoom in/out or pan through the canvas or am I missing some other controls?

**Comment by simonbrowndotje** [comment]
There is no zoom/pan functionality at this time.

**Comment by ODiogoSilva** [comment]
Thanks for the information. Closing as this is expected behaviour.
