### ISSUE TITLE
Add the ability to add clickable links to properties

### ISSUE THREAD

**Issue by FightingFox** [structurizr/ui#63]
### Description

Sometimes you need to add links to swagger, documentation, or something else to the properties of an object. Please add the ability to hover over the tooltip and click on the links posted there.

### Priority

I'm willing to add this feature myself and raise a PR (please confirm approach first)

**Comment by FightingFox** [comment]
@simonbrowndotje, good day.

We need this functionality to place links to various resources in properties. It seems to me that it is quite useful to use.
We are ready to prepare changes and make PR, if you don't mind our idea.

**Comment by FightingFox** [comment]
https://github.com/structurizr/ui/assets/77280748/18d814d7-ff95-4a86-9388-119419dc3168

**Comment by simonbrowndotje** [comment]
"Sticky toolips" are already supported by holding the `Alt` key (https://docs.structurizr.com/ui/diagrams/keyboard-shortcuts#viewing-diagrams) ... is this not working for you?

**Comment by FightingFox** [comment]
Оh, realy. It working, very good.
Thank you.
