### ISSUE TITLE
SVG thumbnails

### ISSUE THREAD

**Issue by OlegKunitsyn** [structurizr/ui#67]
### Description

IMO, there is no reason to convert high-quality scalable SVG to low-quality PNG thumbnails.

With full respect, I forked your project under https://gitlab.com/plgrnd/aac
If you can, please suggest a way how to render SVG server-side via `/workspace/preview/{diagram}`. SSR will help fix blank/eager/lazy thumbnails as well.

### Priority

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment]
> If you can, please suggest a way how to render SVG server-side

Diagrams are rendered client-side (i.e. in your web browser), so server-side rendering isn't possible.
