### ISSUE TITLE
Some firewalls block GET requests with a contentType header.

### ISSUE THREAD

**Issue by hjkiefer** [structurizr/ui#80]
### Expected

It should be possible to run structurizr/lite as a stand-alone server on kubernetes for displaying single diagrams.

### Actual

Running the server works, and I can actually display diagrams on our internal development environment. However, on some servers, it is not possible, since our firewall blocks GET requests with a contentType header.

### Steps to reproduce

This is quite hard, since you need to deploy the server in front of a strict firewall. 

### Version/build information

Any version I have tried.

### Severity

Minor

### Priority

I'm willing to fix this myself and raise a PR (please confirm approach first)

**Comment by simonbrowndotje** [comment]
Thanks for the additional information - I've removed the empty header from GET requests, which should resolve the issue without the need to modify any of the server-side code.
