### ISSUE TITLE
Dark Mode as a Configuration Option

### ISSUE THREAD

**Issue by kieronlanning** [structurizr/ui#82]
### Description

Currently Structurizr (Lite is the only once I've tested) utilises the system/ browser's Dark/ Light mode to display the Documentation/ ADRs by default in that system or browser setting.

This can be overridden by creating a cookie in the client browser called `structurizr.dark` with a value of `false`.

Could a option to switch between these modes be made available within the UI - much like the diagrams have the option to switch between dark/ light mode?

Additionally, could a default be set within the DSL/ Lite configuration?

### Priority

I have no budget and there's no rush, please add this feature for free

### More information

While primarily for display purposes, this could be argued as an accessibility mode. While dark mode is preferable for a lot of reasons, applications like GitLab, Microsoft Word/ Office products - allow a dark mode (for the UI elements) but a light mode for the content to enable easier reading.

**Comment by simonbrowndotje** [comment]
I've added the ability to override dark/light mode via a set of options on the diagrams, documents, and decisions pages. This will be in the next release, but you can build Lite from source if you need this more quickly.

<img width="268" alt="Screenshot 2024-08-22 at 11 01 09" src="https://github.com/user-attachments/assets/74436da9-2f9d-4b13-a851-06305d976c4e">

**Comment by kieronlanning** [comment]
Amazing! Thanks @simonbrowndotje!
