### ISSUE TITLE
Embedding diagrams does not resize correctly if embedded within a Shadow DOM.

### ISSUE THREAD

**Issue by RowlandBanks** [structurizr/ui#84]
### Expected

I expect an embedded diagram to have the correct height to maintain aspect ratio when embedded inside a shadow DOM.

### Actual

The diagram has the height of the initial iframe, and does not ensure the correct aspect ratio is maintained.

### Steps to reproduce

Rename [index.txt](https://github.com/user-attachments/files/16848161/index.txt) to `index.html`.

Set the following lines appropriately for your test environment.

```js
const root = "http://localhost:8081";
const workspaceId = "1";
const diagramId = "SystemContext-001";
```

Host `index.html` in a web-server somewhere (e.g. you could use a `docker-compose.yml` to host it in Nginx like so:)

```yml
services:
  # docker compose up -d --build --remove-orphans --force-recreate
  web:
    image: nginx:alpine
    volumes:
      - "./web:/usr/share/nginx/html/"
    ports:
      - "8080:80"
```

Then navigate to `http://localhost:8080/index.html` and you will see the Actual result.

### Version/build information

onpremises 2024.06.25

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

### More information

I am writing a TechDocs plugin for Backstage that will embed a Structurizr diagram into a Backstage TechDocs page.

(This is not possible natively, because TechDocs removes iframes and scripts for security reasons).

TechDocs is a React application, and so renders the document inside a shadow DOM, like so (rename to index.html):

[index.txt](https://github.com/user-attachments/files/16848161/index.txt)

However, the `structurizr-embed.js` script does not support looking in a shadow DOM so it is unable to find the `iframe` element.

One approach to fixing it is to update the `structurizr-embed.js` document to search the whole DOM, including shadow roots:

```js
    function getElement(id, root) {
        root = root || document;
        if (root.shadowRoot) {
            const element = root.shadowRoot.getElementById(id);
            if (element) return element;
        }
        
        for (const child of root.children) {
            const result = getElement(id, child);
            if (result) return result;
        }

        return null;
    }
```

A full example is here (rename extension to `.js`).

[structurizr-embed.txt](https://github.com/user-attachments/files/16848249/structurizr-embed.txt)

Another approach to fixing it would be to pass the `id` of the shadow root element as part of the embed URL, so that the script can find the element directly.

**Comment by simonbrowndotje** [comment]
Thank you for the comprehensive details on this!

**Comment by RowlandBanks** [comment]
No probs - thanks for the quick response :)
